# Generated by Django 2.2 on 2020-06-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('subject', models.TextField(default='')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('user_recommend', models.CharField(choices=[('1', 'definetely'), ('2', 'maybe'), ('3', 'not Sure')], default='', max_length=2)),
                ('role', models.CharField(choices=[('1', 'individual'), ('2', 'couple'), ('3', 'smallgroup'), ('4', 'largegroup'), ('5', 'preferno')], default='', max_length=2)),
                ('prefer', models.TextField(blank=True, max_length=30, null=True)),
                ('purpose', models.CharField(choices=[('1', 'Date'), ('2', 'birthday'), ('3', 'anniversary'), ('4', 'party')], default='', max_length=2)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
