# Generated by Django 2.2 on 2020-06-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='user_recommend',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
