# Generated by Django 2.2 on 2020-06-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200602_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='user_recommend',
        ),
    ]
